### ISSUE TITLE
classic-keybindings not loading

### ISSUE THREAD

**Issue by OrionRandD** [EFLS/zetteldeft#109]
I use doom-emacs and classic-keybinding are not loading upon starting Emacs.
here is my config:

(use-package! zetteldeft
  :after deft
  :config
  (zetteldeft-set-classic-keybindings)
  (setq deft-new-file-format zetteldeft-id-format)
  )

**Comment by EFLS** [comment]
Not really familiar with the Doom-way, but since you use `:after deft`, the question is: when is Deft loaded? Can you test either (1) dropping the `:after` line, or (2) replacing `:config` with `:init`?

Also `(setq deft-new-file-format zetteldeft-id-format)` is not needed as this is already part of `zetteldeft.el`.

**Comment by OrionRandD** [comment]
> Not really familiar with the Doom-way, but since you use `:after deft`, the question is: when is Deft loaded? Can you test either (1) dropping the `:after` line, or (2) replacing `:config` with `:init`?
> 
> Also `(setq deft-new-file-format zetteldeft-id-format)` is not needed as this is already part of `zetteldeft.el`.

worked with this setup

(use-package! zetteldeft
  ;; :after deft
  :init
  (zetteldeft-set-classic-keybindings)
  ;; (setq deft-new-file-format zetteldeft-id-format)
  )

Thx a lot 
:)
