### ISSUE TITLE
Scandinavian letters do not work properly on tags

### ISSUE THREAD

**Issue by AulisVainionpaa** [EFLS/zetteldeft#110]
Hi
I have problems using Finnish words in tags, they don't show up correctly in the tag search or even when they are added to the text.

Here is an example of text that I would like to display correctly:

`#ylläpito #käynnistys`

And this is what it looks like in searches and notes:

`#yll #k`

For those who want to know what the words mean:
ylläpito = system maintenance
käynnistys = booting

Sorry my bad english and possibly a poorly explained problem, unfortunately I can't explain it better.

My Emacs and Zetteldeft info:
GNU Emacs 27.1
zetteldeft-20210409.2126

**Comment by EFLS** [comment]
Can you be a bit more specific in what you mean with "what it looks like in searches and notes?" What functions are you using specifically? Just provide the steps to reproduce the issue.

What happens when you try to do a regular Deft search for words with those characters? (e.g. with `C-c d D`)

I have a hunch this is related to Deft itself. Deft doesn't seem to handle non-Latin characters very well in some cases. Do you use a specific input method within Emacs? See also https://github.com/jrblevin/deft/issues/59

**Comment by AulisVainionpaa** [comment]
Ok. Thanks for your information.

**Comment by EFLS** [comment]
Were you able to solve your issue? Feel free to ask follow up questions if you still have issues

**Comment by AulisVainionpaa** [comment]
This isn't Zetteldeft issue, more like Deft issue.
