### ISSUE TITLE
zd IDs not linking

### ISSUE THREAD

**Issue by anthrolisp** [EFLS/zetteldeft#14]
zd IDs are not linking to their respective documents, regardless of how they generated, either manually or automated by "zd-find-file-id-insert", etc. 

e.g. 

- §2019-03-07-2215 Title A
- §2019-03-07-2213 Title B
- §2019-03-07-2308 
- §2019-03-08-1352 Title C

How to make these IDs links to their respective document? Am I missing something?  Many thanks in advance!! 

Sorry to overwhelm you with issues! I really love and appreciate what you are doing with zetteldeft, and am slowing moving everything over to it. Thanks again!

**Comment by anthrolisp** [comment]
I think I understand now. These are not supposed to appear within org-mode like regular org links that are clickable. Instead, one follows them as links with "zd-avy-file-search". If this is case, feel free to close the issue! Many thanks in advance!

**Comment by EFLS** [comment]
Yup, that's exactly it.

Since this package and its functions grew organically, the documentation may also be lacking. I should think of providing a clearer "get started" type of entry point for new users.

An overview of functions can be found under heading 1.5 in the [documentation](https://efls.github.io/zetteldeft/).

**Comment by anthrolisp** [comment]
I also think a short screencast showing what zetteldeft can do, idea of zettelkasten, workflow, etc would be good for those who have not heard of it.
