### ISSUE TITLE
Is this expected behavior for dynamic blocks?

### ISSUE THREAD

**Issue by elliottw** [EFLS/zetteldeft#141]
I have a file titled "doing". In doing I have several dynamic blocks, one for projects (searches for #active-project), one for books I'm reading (searches for #active-books). In each of the dynamic blocks, I have a link to the file titled "doing" which is the same file I am in. This happens in all files with dynamic blocks.

**Comment by EFLS** [comment]
Hi, no this is not expected behaviour. The currently visited file should be filtered out from the results. Not sure what's going on there, I'd have to look into it.

**Comment by elliottw** [comment]
I am creating the same list using dynamic blocks and zd-insert-list-links. Both have the current file in the list. Now I'm wondering if this is a bug in deft because my file titled "doing" is showing twice in the deft view. If I refresh deft, then one of those duplicate line items goes away.

**Comment by elliottw** [comment]
Regarding your second comment about no longer actively developing Zetteldeft, would you say that's because it's stable and feature complete and you still use it and have no reservations in others continuing to use it as is?

**Comment by EFLS** [comment]
> Now I'm wondering if this is a bug in deft because my file titled "doing" is showing twice in the deft view. If I refresh deft, then one of those duplicate line items goes away.

The list is generated via a Deft search, so if it appears twice in Deft it will be twice in the list (and only removed once when you are in that note calling the function)

> Regarding your second comment about no longer actively developing Zetteldeft, would you say that's because it's stable and feature complete and you still use it and have no reservations in others continuing to use it as is?

I think it is fairly stable, having used it for a long time. I'm currently exploring how to implement these features in Denote, which provides more stability in the long run (as compared to Deft). So the only reason I'm no longer actively developing is because I don't use it daily myself, but I'm happy others still find value in it.

**Comment by elliottw** [comment]
Thanks for the response. This is definitely a deft thing, so I guess from the zd perspective, this issue can be closed.
