### ISSUE TITLE
Feature Request: ability to change format of title

### ISSUE THREAD

**Issue by mediapathic** [EFLS/zetteldeft#17]
Note: this is probably considered a subset of #5. I'm not sure if it's appropriate to file as a separate issue, but I think so.

I am using zetteldeft to create markdown notes, which is working well with the changes you've made re: #5. One of the few issues I have still is that the title is always inserted in org format. What I use for the "title" is very similar, but instead of 

`#+title: 201905040327 test file`
I use
`# 201905040327 test file`

Looking at the internals, it seems that this format is hardcoded. I propose setting a variable for the prefix, set the way you do it by default, which any user could change in an init file (or maybe in customize, but I don't know how much extra work that is for you). This would also open up opportunities for others to include custom formatting for titles should it be needed.

**Comment by rotlaus** [comment]
Currently the title is '#+title:' + filename without extension.
Do we want a customizable prefix (default '#+TITLE:') + filename without extension? 
What about a variable zd-title-prefix and then we should rename zd-insert-org-title to zd-insert-title. Only Problem i currently  see is how the rename function could work with an empty prefix.
Otherwise i could work on that.

**Comment by mediapathic** [comment]
I hadn't even thought about the impact on the rename function, since, because I don't use org-style `#+title 201905240117 title` and instead use markdown style `# 201905240117 title `, rename only affects filenames for me. 

That said, what I would personally prefer would be just setting a customizable prefix as per your first suggestion.

**Comment by EFLS** [comment]
This should be fixed with the latest commit: df7228a.

There are now two customizable variables:
- `zd-title-prefix`
- `zd-title-suffix` (previously `zd-string-after-title`, make sure to update your configuration)

This means that the function `zd-file-rename` should now also work for the customized title prefixes.

@mediapathic could you test this out? Make sure to first set `zd-title-prefix` to "# ", and then try to use `zd-file-rename`.

**Comment by mediapathic** [comment]
Sorry it took me a while to get to this. It seems to work great! And now I have title renaming as a bonus! Thanks so much.
