### ISSUE TITLE
zd--check "not in zetteldeft territory"

### ISSUE THREAD

**Issue by sjhogerzeil** [EFLS/zetteldeft#3]
When I use zd-new-file I keep getting the user-error "Not in zetteldeft territory.", probably because the zd--check function concludes that my file does not have the deft-directory in it's path. But I have checked, and this is untrue.

It looks like the buffer created (before being saved) does not match the criteria of zd--check, but after being saved in to deft-directory it would. 

Kind regards, Simon Hogerzeil

**Comment by EFLS** [comment]
Hi Simon,

As long as you don't save, there is no file path to check, so `zd--check` will indeed throw an error. The simplest solution is to quickly (and manually) save after creating a new note.
Maybe I could add a line so that zetteldeft saves the note as soon as its created. I'll look into it.

Cheers
EFLS

**Comment by EFLS** [comment]
Figured I might as well throw a `save-buffer` in there. Should be fixed now.
