### ISSUE TITLE
Add variable to specify a prefix to the filename

### ISSUE THREAD

**Issue by beetleb** [EFLS/zetteldeft#30]
Can we have a variable where the user can specify a prefix for the filename? After adding so many notes in one Emacs session I'll have lots of buffers open. I'd like to be able to kill them all easily, and if they all began with a prefix it would be quite easy.

**Comment by EFLS** [comment]
Don't they all have a prefix, since they start with the link ID?

**Comment by beetleb** [comment]
Say I've been using zetteldeft for 5 years. So I'll have open buffers beginning with 2018, 2019, 2020, 2021, 2022. How would you propose I quickly kill all zetteldeft buffers? A pattern match for "20[12]*"?

The likelihood that I'll have some file open that begins with "2019" and is *not* a Zetteldeft note is not insignificant. Beginning file names with the year is a common pattern in general. If I could prefix all my filenames with "zettel", for example (or even "zd-"), then it's trivial to write close all Zetteldeft buffers.

(BTW, not insisting you write the code to solve the problem - just wanted to open the issue so that anyone can submit a MR).

**Comment by EFLS** [comment]
> Say I've been using zetteldeft for 5 years. So I'll have open buffers beginning with 2018, 2019, 2020, 2021, 2022.

Only if you've been running the same emacs instance for five years, no?

That said, like you suggest, it's a simple issue that someone might want to submit an MR for. Althrough there might be complications (like stripping it when retreiving the title from a note), I'm not against something like that by itself.

**Comment by beetleb** [comment]
> Only if you've been running the same emacs instance for five years, no?

Nope. Any time I open a note it opens it as a file. So if I am in an Emacs session and look up 10-20 things in my Zettelkasten system, I could have files open from each year.

> No, a pattern match for zetteldeft-id-regex. That might exlcude other buffers.

That may be good enough. Thanks.

> That said, like you suggest, it's a simple issue that someone might want to submit an MR for.

You know, later today I was wondering about something else. I'll probably want to modify the ID to my own liking anyway. I don't know if you expose it, but perhaps allow the user to specify his/her own function to generate an ID/filename. The reason is that I realize I don't want the title in the file name. ZD requires me to supply the title up front, while the thought in my head is still nebulous. All too often when I'm done typing the note I realize the title is off compared to the contents, and I edit the title. But the filename remains the original one I had put for the note. When searching for things in deft this can be misleading.

I suppose if I'm going to modify the way one specifies the filename/ID, then I can add the prefix in there as well.

**Comment by EFLS** [comment]
> Any time I open a note it opens it as a file. So if I am in an Emacs session and look up 10-20 things in my Zettelkasten system, I could have files open from each year.

Ah yes, of course.

> ZD requires me to supply the title up front, while the thought in my head is still nebulous. All too often when I'm done typing the note I realize the title is off compared to the contents, and I edit the title.

Yeah, renaming is important. Check out the function `zetteldeft-file-rename`. It renames both the file and the `#+TITLE:` in the file (or whatever the value is of `zetteldeft-title-prefix`).

> I don't know if you expose it, but perhaps allow the user to specify his/her own function to generate an ID/filename.

That's what `zetteldeft--insert-title` does. You can experiment with redefining it if you want more flexibility.

Remember to check those out in the full documentation: https://efls.github.io/zetteldeft

Let me know how it goes and whether this suits your use case. I'm always interested in learning how people adapt `zetteldeft` to fit their workflow.

**Comment by gklimowicz** [comment]
This is probably out of scope for a request, but since I use `zetteldeft-new-file-and-link` a lot, it would be neat if the file rename could be reflected in the notes that reference the renamed note.

This might be like walking the results of `zetteldeft-search-current-id` and doing the title replaces in those notes...

(The shell scripts I wrote do this, but I haven't imported the ability into Emacs yet.)

**Comment by EFLS** [comment]
> it would be neat if the file rename could be reflected in the notes that reference the renamed note.

I've thought about that as well, but haven't attempted to write anything for it. I rarely refer to notes by their full name (or when I do it is via an automated list, which will reflect the new filename automatically, as discussed here: https://github.com/EFLS/zd-tutorial/blob/master/2020-04-17-1611%20Automated%20lists%20of%20links.org). That said, I'm open to contributions in this direction.

This is really a separate topic from what is being discussed here. Feel free to open a separate issue for this, or even submit a PR if you write such a function.

**Comment by TRSx80** [comment]
I'm a bit lost as to what the scope of this issue really is.  So I will try to summarize.

OP starts out talking about problem X (variable prefix to file name).  After some discussion, it turns out the problem actually is Y (he wants to be able to close many buffers with a single command).  So far looks a lot like textbook [XY Problem](http://xyproblem.info/).

However I think problem Y eventually gets solved (see [here](https://github.com/EFLS/zetteldeft/issues/30#issuecomment-577482029)), where OP states:

> > No, a pattern match for zetteldeft-id-regex. That might exlcude other buffers.
> 
> That may be good enough. Thanks.

And if so, shouldn't this issue be closed?  You OK with that @beetleb?

Or are we tracking this as issue Y now?  In which case perhaps we should change title (and I could maybe whip up said function, if that is something we want to have in Zetteldeft (up to @EFLS))?

Assuming of course that whatever @gklimowicz was talking about should be discussed in a separate issue (not sure if that even exists yet).

Have I got all of that about right?  I suppose I'm just trying to help clean up / triage the issue list.

Cheers!

**Comment by beetleb** [comment]
I'm OK with closing this.

**Comment by EFLS** [comment]
Thanksk for chipping in @TRSx80. I'll close this as it seems like the actual problem Y is solved, more or less.

What @gklimowicz raises is a different issue altogether, I think, so should be discussed separately.
