### ISSUE TITLE
Question: Why custom link format instead of org-mode links?

### ISSUE THREAD

**Issue by pmiddend** [EFLS/zetteldeft#40]
Just a question, really, but why didn't you opt for org-mode links instead of the custom link format with the special character?

**Comment by EFLS** [comment]
There are a couple of reasons for this.
- Currently, Zetteldeft is not limited to org-mode, but can be used in and from any mode.
- Org-mode links might break when files are moved or the filename changes.
- I want to prevent lock in as much as possible. Many people use a Markdown-based system, and you could perfectly use Zetteldeft together with other applications (theoretically at least -- I might need to change)

And the link indicator can be customized if you want to. Ideally, I should look for a way to make it work with [[these types]] of links, so that it plays nicely with [The Archive](https://zettelkasten.de/the- archive/), for example, but that's for some point in the future.

**Comment by pmiddend** [comment]
@EFLS Excellent answer, thanks for writing that up and thanks for the link. What you tried there was exactly what I was going to approach next.
And thanks for Zetteldeft in general, it works really well so far for me.

**Comment by EFLS** [comment]
Welcome, please let me know if you have further ideas and suggestions!
