### ISSUE TITLE
Race condition in "generate and link" functions

### ISSUE THREAD

**Issue by pmiddend** [EFLS/zetteldeft#60]
Disclaimer: maybe I'm reading the code wrong, I'm not an elisp expert.

Looking at the `zetteldeft-new-file-and-link` function, I'm a bit confused. This function

1. generates a new ID, and inserts a link to the new file using that ID
2. calls `zetteldeft-new-file`, which _again_ generates an ID

So, does the `new-file-and-link` function assume that both generated IDs are the same? I assume they _might_ be, because the ID uses the current time. However, what if the ID changes between step 1 and 2? That's a classic race condition and it's *extremely* hard to spot the mistake if it happens.

A way better solution would be to pass the generated ID to the "new file" function as an optional argument.

Am I wrong in my analysis of the code and the resulting possible error?

**Comment by EFLS** [comment]
Well spotted! I have no clue what "race conditions" are (forgive the ignorance of a non-programmer), but the ID is indeed generated twice. Because by default the ID is time-based, it might not be a real problem, but who knows when this becomes an issue.

I'll see whether it is best to pass the generated ID, or to refrain from using `zetteldeft-new-file` in the `new-file-and-link` function.

It also seems the documentation is a bit outdated too, I should change this.

**Comment by EFLS** [comment]
I've changed `zetteldeft-new-file` so that it now accepts an ID. Should be fixed now!
