### ISSUE TITLE
Inserts texts when clicking on zettel with mouse

### ISSUE THREAD

**Issue by anthrolisp** [EFLS/zetteldeft#8]
When clicking on a zettel from inside zetteldeft buffer, it opens the zettel as expected but also automatically inserts/pastes text into zettel. The inserted text seems to be whatever was previously highlighted by the cursor, whether in emacs or other program such as Firefox. This behaviour does not happen when one opens a zettel from the zetteldeft buffer by hitting "return". Any thoughts?

**Comment by EFLS** [comment]
> as expected

Not really expected, since I didn't include any feature that would allow clicking to follow links. What types of links are you using?

Afaik clicking behaviour is related to other emacs functionality. For example, when I click anywhere in my buffer and a region (i.e. text selection) is active, it will indeed paste that text. I don't think this is related to `zetteldeft`.

**Comment by anthrolisp** [comment]
You are correct, seems to be a common issue in EMACS 25/ Spacemacs. The following seems to fix the problem:

;; https://github.com/syl20bnr/spacemacs/issues/5435
(add-hook 'prog-mode-hook (lambda () (set (make-local-variable 'mouse-1-click-follows-link) nil)))

Thank you.

**Comment by EFLS** [comment]
Glad that you fixed it! I'll close this issue.
