### ISSUE TITLE
zd-avy-tag-search "wrong type argument" error

### ISSUE THREAD

**Issue by termitereform** [EFLS/zetteldeft#9]
Hello! 

Within the last week or two, I started getting errors when trying to use zd-avy-tag-search, specifically:

`avy--regex-candidates: Wrong type argument: number-or-marker-p, at-full`

Just to eliminate possible problems, I made a new init in a clean .emacs.d directory that loaded only the current versions of deft, avy, and the zetteldeft -- still got the error. I'm on Windows.

The backtrace looks like this:

`Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p at-full)`
`  avy--find-visible-regions(at-full 348)`
`  avy--regex-candidates("[#@][a-z-]+" at-full nil)`
` avy--generic-jump("[#@][a-z-]+" nil at-full)`
` (save-excursion (avy--generic-jump zd-tag-regex nil avy-style) (zd-search-at-point))`
` zd-avy-tag-search()`
` funcall-interactively(zd-avy-tag-search)`
` call-interactively(zd-avy-tag-search record nil)`
` command-execute(zd-avy-tag-search record)`
` execute-extended-command(nil "zd-avy-tag-search" "zd-avy-ta")`
` funcall-interactively(execute-extended-command nil "zd-avy-tag-search" "zd-avy-ta")`
` call-interactively(execute-extended-command nil nil)`
` command-execute(execute-extended-command)`

And an example zettel looks like this:

> ﻿#+title: 20190217213916 Omar Khayyam on Paradise
>
>Tags: #quotebox #cargocult #romance
>
>CF: §20190217213730 for Anacreon's take on the same idea
>
>#+begin_quote
>A Book of Verses underneath the Bough,
>A Jug of Wine, a Loaf of Bread—and Thou
>Beside me singing in the Wilderness—
>Oh, Wilderness were Paradise enow!
>        -- Omar Khayyam, "Quatrain XII", from
>           _The Rubaiyat of Omark Khayyam (1889 Edition)_ 
>           [Edward FitzGerald, Translator]
>#+end_quote

**Comment by EFLS** [comment]
Thanks for the detailed report.

After looking into it, I figure the issue is [this recent change](https://github.com/abo-abo/avy/commit/e80251056de24ef67b12d4e81f5aba45d3719c7c) to `avy` which replaces `avy--generic-jump` with `avy-jump`.

I didn't run into the issue myself yet, since I haven't updated `avy` yet.

Should be easy to fix, but I don't want to break things for people that are not updating to the most recent `avy` just yet... I'll look into it later this week.

If you want a fix in the meantime, try to load an earlier version of `avy`.

**Comment by termitereform** [comment]
I thought that might be the case -- the only thing I'd done to change my setup since last week was updating packages. 

Thanks for looking into it! And thanks for this awesome set of tools!

**Comment by EFLS** [comment]
Commit 15e99dc9a3de8bde969b97d1d8c89232df262aad should fix this!
